version: '3.4'

services:
  api:
    build:
      context: ./api
      target: development
    image: development
    entrypoint: ./wait-for-it.sh db 27017
    environment:
      FLASK_ENV: development
      ENVIRONMENT: local
      MONGO_INITDB_ROOT_PASSWORD: maf
    volumes:
      - ./home/:/home

  web:
    volumes:
      - ./home/runnable.js:/code/src/runnable.js

  db:
    environment:
       MONGO_INITDB_ROOT_PASSWORD: maf
